# Tmux Hierarchy is - Sessions ---> Windows ---> Panes

#Keybinding
unbind r
bind r source-file ~/.config/tmux/tmux.conf

#Global settings
set -g mouse on
set -g prefix C-a
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g allow-passthrough on
set -g pane-border-status top
set -g pane-border-format "#[align=centre] #{pane_title}"
set -g status-position bottom

#Setting some optimal keybinds
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

#Set the environment variables
set-env -g TMUX_POWERLINE_CONFIG_FILE "$HOME/.config/tmux-powerline/config.sh"

# Tmux plugins init
set -g @plugin 'erikw/tmux-powerline'

#Script to run all the tmux plugins
run '~/.tmux/plugins/tpm/tpm'
