# Tmux Hierarchy
# 
#	Sessions ---> Windows ---> Panes

unbind r
bind r source-file ~/.config/tmux/tmux.conf

#To keep the mouse on
set -g mouse on

#Change the prefix binding
set -g prefix C-a

#Setting up index 1 for panes and windows
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

#For the tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'

#For oasis theme
set -g @plugin 'uhs-robert/tmux-oasis'
set -g @plugin 'starlight'

#For ubuntu terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

run '~/.tmux/plugins/tpm/tpm'
